# Generated by Django 2.1.1 on 2018-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentor_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('CO', 'Computer'), ('IT', 'InformationTechnology'), ('MECH', 'Mechanical'), ('EXTC', 'Electronics')], max_length=1)),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
    ]
