# Generated by Django 2.1.1 on 2018-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_detail',
            name='department',
            field=models.CharField(choices=[('CO', 'Computer'), ('IT', 'InformationTechnology'), ('MECH', 'Mechanical'), ('EXTC', 'Electronics')], max_length=4),
        ),
    ]
